trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

pr: none

variables:
  buildConfiguration: 'release'

stages:
- stage: build_image
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: "DAS - Continuous Integration"
      demands: Agent.OS -equals Linux
    steps:
      - task: UseGitVersion@5
        inputs:
          versionSpec: 5.x
          useConfigFile: true
          configFilePath: GitVersion.yml

      - task: Docker@2
        displayName: Build Image
        inputs:
          command: build
          dockerfile: Dockerfile
          repository: apprenticeshipsdevops/das-tools-servicebus-support
          tags: $(build.buildnumber)

      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: "Apprenticeships DevOps Docker Hub"

      - task: Docker@2
        displayName: Push Image
        inputs:
          command: push
          repository: apprenticeshipsdevops/das-tools-servicebus-support
          tags: $(build.buildnumber)

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          contents: |
            azure/**
            manifests/**
          targetFolder: '$(build.artifactstagingdirectory)/publish'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          pathtoPublish: '$(build.artifactstagingdirectory)/publish'

- stage: Build_function
  displayName: Build function
  jobs:
  - job: build_function
    displayName: Build function
    pool:
      name: "DAS - Continuous Integration"
      demands: Agent.OS -equals Linux
    steps:
      - task: UseGitVersion@5
        inputs:
          versionSpec: 5.x
          useConfigFile: true
          configFilePath: GitVersion.yml

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: 'src/SFA.DAS.Tools.Servicebus.Support.Functions/SFA.DAS.Tools.Servicebus.Support.Functions.csproj'
          noCache: true

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: 'src/SFA.DAS.Tools.Servicebus.Support.Functions/SFA.DAS.Tools.Servicebus.Support.Functions.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore'

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: '**/*.UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --no-build'

      - task: DotNetCoreCLI@2
        displayName: 'Publish Work Function App'
        inputs:
          command: publish
          publishWebProjects: false
          projects: 'src/SFA.DAS.Tools.Servicebus.Support.Functions/SFA.DAS.Tools.Servicebus.Support.Functions.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          pathtoPublish: '$(build.artifactstagingdirectory)/publish'
