trigger:
  batch: true
  branches:
    include:
      - QUAL-645-DirectAADLogin
  paths:
    include:
      - azure/*
      - src/*
      - pipeline-templates/*
      - azure-pipelines.yml

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.2.6
    endpoint: GitHub (SFA)
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.2.2
    endpoint: GitHub (SFA)

pr: none

variables:
- group: Release Management Resources
- group: Wildcard Cert Variables v2

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-tools-servicebus (temp)
  jobs:
  - template: azure-pipelines-templates/deploy/job/arm-deploy.yml@das-platform-building-blocks
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ToolsServiceBusArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsServiceBusArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)
        AzureAdConfigurationClientSecret: $(AzureAdConfigurationClientSecret)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsServiceBusArtifacts/SFA.DAS.Tools.Servicebus.Support.Web.csproj

  ## TO DO DEPLOY FUNCTION APP  - NEED TO CREATE BULDING BLOCKS