---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: '{{UserManagedIdentityName}}-binding'
spec:
  azureIdentity: {{UserManagedIdentityName}}
  selector: {{UserManagedIdentityName}}
